version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend/my-react-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
